# Snowflake MCP Server Configuration
agent_services: true
search_services: true
analyst_services: true

other_services:
  object_manager: true        # list databases/schemas/tables/columns
  query_manager: true         # execute SQL (obeys permissions below)
  semantic_manager: false     # keep off unless you actually want them

sql_statement_permissions:
  - select: true
  - show: true
  - describe: true

